# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d7c2fdff682bee466038b49b3eafdbf8"
name = "host-test-app"
handle = "host-test-app"
application_url = "https://completely-commonly-going-september.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "api-testing-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://completely-commonly-going-september.trycloudflare.com/auth/callback",
  "https://completely-commonly-going-september.trycloudflare.com/auth/shopify/callback",
  "https://completely-commonly-going-september.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
